;;; apropospriate-theme-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from apropospriate-dark-theme.el

(register-definition-prefixes "apropospriate-dark-theme" '("apropospriate-dark"))


;;; Generated autoloads from apropospriate-light-theme.el

(register-definition-prefixes "apropospriate-light-theme" '("apropospriate-light"))


;;; Generated autoloads from apropospriate-theme.el

(and load-file-name (boundp 'custom-theme-load-path) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "apropospriate-theme" '("apropospriate-" "create-apropospriate-theme"))

;;; End of scraped data

(provide 'apropospriate-theme-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; apropospriate-theme-autoloads.el ends here
