local M = {}

M.border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" }

M.kind = {
        Break = "󰙧",
        Call = "󰃷",
        Case = "󰬶",
        Class = "󰠱",
        Color = "󰏘",
        Constant = "󰏿",
        Constructor = "",
        Continue = "󰞘",
        Declaration = "󰙠",
        Delete = "󱟁",
        Enum = "",
        EnumMember = "",
        Event = "",
        Field = "󰇽",
        File = "󰈙",
        Folder = "󰉋",
        Fragment = "",
        Function = "󰊕",
        Implementation = "",
        Interface = "",
        Keyword = "󰌋",
        List = "󰅪",
        Loop = "󰑖",
        Method = "󰆧",
        Module = "",
        Namespace = "󰌗",
        Operator = "󰆕",
        Package = "",
        Property = "󰜢",
        Reference = "",
        Regex = "",
        Snippet = "",
        Statement = "󰅩",
        Struct = "",
        Switch = "",
        Text = "󰉿",
        TypeParameter = "󰅲",
        Undefined = "",
        Unit = "",
        Value = "󰎠",
        Variable = "",
        -- ccls-specific icons
        Macro = "",
        Parameter = "",
        StaticMethod = "",
        Terminal = "",
        TypeAlias = "",
}

M.type = {
        Array = "󰅪",
        Boolean = "",
        Null = "󰟢",
        Number = "",
        Object = "󰅩",
        String = "󰉿",
}

M.documents = {
        Default = "",
        File = "",
        Files = "",
        FileFind = "󰈞",
        FileTree = "󰙅",
        Import = "",
        Symlink = "",
        Word = "",
}

M.git = {
        Add = "",
        Branch = "",
        Diff = "",
        Git = "󰊢",
        Ignore = "",
        Mod = "M",
        Mod_alt = "",
        Remove = "",
        Rename = "",
        Repo = "",
        Unmerged = "󰘬",
        Untracked = "󰞋",
        Unstaged = "",
        Staged = "",
        Conflict = "",
}

M.ui = {
        Accepted = "",
        ArrowClosed = "",
        ArrowOpen = "",
        BigCircle = "",
        BigUnfilledCircle = "",
        BookMark = "󰃃",
        Buffer = "󰓩",
        Bug = "",
        Calendar = "",
        Character = "",
        Check = "󰄳",
        ChevronRight = "",
        Circle = "",
        Close = "󰅖",
        Close_alt = "",
        CloudDownload = "",
        CodeAction = "󰌵",
        Comment = "󰅺",
        Dashboard = "",
        DoubleSeparator = "󰄾",
        Emoji = "󰱫",
        EmptyFolder = "",
        EmptyFolderOpen = "",
        File = "󰈤",
        Fire = "",
        Folder = "",
        FolderOpen = "",
        FolderWithHeart = "󱃪",
        Gear = "",
        History = "󰄉",
        Incoming = "󰏷",
        Indicator = "",
        Keyboard = "",
        Left = "",
        List = "",
        Lock = "󰍁",
        Modified = "✥",
        Modified_alt = "",
        NewFile = "",
        Newspaper = "",
        Note = "󰍨",
        Outgoing = "󰏻",
        Package = "",
        Pencil = "󰏫",
        Perf = "󰅒",
        Play = "",
        Project = "",
        Right = "",
        RootFolderOpened = "",
        Search = "󰍉",
        Separator = "",
        SignIn = "",
        SignOut = "",
        Sort = "",
        Spell = "󰓆",
        Square = "",
        Symlink = "",
        SymlinkFolder = "",
        Tab = "",
        Table = "",
        Telescope = "",
        Window = "",
}

M.lang = {
        lua = { icon = "", color = "#51A1FF" },
        python = { icon = "", color = "#FFD43B" },
        javascript = { icon = "", color = "#F7DF1E" },
        html = { icon = "", color = "#E34C26" },
        css = { icon = "", color = "#264de4" },
        json = { icon = "", color = "#cbcb41" },
        markdown = { icon = "", color = "#519aba" },
        vim = { icon = "", color = "#019833" },
        sh = { icon = "", color = "#89e051" },
        gd = { icon = "", color = "#478cbf" },
        gdscript = { icon = "", color = "#478cbf" },
        toml = { icon = "", color = "#6e6e6e" },
        xml = { icon = "謹", color = "#e37933" },
        yaml = { icon = "", color = "#6e6e6e" },
        dockerfile = { icon = "", color = "#0db7ed" },
        go = { icon = "󰊠", color = "#00ADD8" },
        rust = { icon = "", color = "#dea584" },
        c = { icon = "", color = "#555555" },
        cpp = { icon = "", color = "#00599C" },
        java = { icon = "", color = "#b07219" },
        php = { icon = "", color = "#8892be" },
        ruby = { icon = "", color = "#701516" },
        swift = { icon = "", color = "#ffac45" },
        tsx = { icon = "", color = "#2b7489" },
        jsx = { icon = "", color = "#61dafb" },
}

M.diagn = {
        error = "󰯈",
        warning = "",
        information = "",
        question = "",
        hint = "",
}

M.misc = {
        Add = "+",
        Added = "",
        Campass = "󰀹",
        Code = "",
        Gavel = "",
        Ghost = "󰊠",
        Glass = "󰂖",
        Lego = "",
        LspAvailable = "󱜙",
        ManUp = "",
        Neovim = "",
        NoActiveLsp = "󱚧",
        PyEnv = "󰢩",
        Squirrel = "",
        Tag = "",
        Tree = "",
        Vbar = "│",
        Vim = "",
        Watch = "",
}

M.dap = {
        Breakpoint = "󰝥",
        BreakpointCondition = "󰟃",
        BreakpointRejected = "",
        LogPoint = "",
        Pause = "",
        Play = "",
        RunLast = "↻",
        StepBack = "",
        StepInto = "󰆹",
        StepOut = "󰆸",
        StepOver = "󰆷",
        Stopped = "",
        Terminate = "󰝤",
}

return M
