#!/usr/bin/env bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

sketchybar --bar position=top height=30 blur_radius=0 color=0xff25252d

default=(
    padding_left=0
    padding_right=0
    icon.font="Maple Mono NF:Bold:14.0"
    label.font="Maple Mono NF:Semibold:14.0"
    icon.color=0xffAAB3C0
    label.color=0xffAAB3C0
    icon.padding_left=2
    icon.padding_right=2
    label.padding_left=2
    label.padding_right=2
    updates=on
)
sketchybar --default "${default[@]}"

##### Adding aeropsace layouts #####
# Add the aerospace events we specified in aerospace.toml
sketchybar --add event aerospace_workspace_change
sketchybar --add event aerospace_monitor_change

for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        display="$(
            v=$(aerospace list-windows --workspace "$sid" --format "%{monitor-appkit-nsscreen-screens-id}" | cut -c1)
            echo "${v:-1}"
            )" \
                drawing=off \
                background.color=0x44ffffff \
                background.corner_radius=0 \
                background.drawing=on \
                background.border_color=0xAAFFFFFF \
                background.border_width=0 \
                background.height=25 \
                icon="$sid" \
                icon.padding_left=10 \
                icon.shadow.distance=4 \
                icon.shadow.color=0xA0000000 \
                label.padding_right=20 \
                label.padding_left=0 \
                label.y_offset=-1 \
                label.shadow.drawing=off \
                label.shadow.color=0xA0000000 \
                label.shadow.distance=4 \
                click_script="aerospace workspace $sid" \
                script="$CONFIG_DIR/plugins/aerospace.sh $sid"
            done

# Load Icons on startup
for mid in $(aerospace list-monitors | cut -c1); do
    for sid in $(aerospace list-workspaces --monitor $mid --empty no); do
        apps=$(aerospace list-windows --workspace "$sid" | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')

        sketchybar --set space.$sid drawing=on

        icon_strip=" "
        if [ "${apps}" != "" ]; then
            while read -r app; do
                icon_strip+=" $($CONFIG_DIR/plugins/icon_map_fn.sh "$app")"
            done <<<"${apps}"
        else
            icon_strip=""
        fi
        sketchybar --set space.$sid label="$icon_strip"
    done
done

sketchybar --add item space_separator left \
    icon.padding_left=0 \
    label.drawing=off \
    background.drawing=off \
#!/usr/bin/env bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

sketchybar --bar position=top height=30 blur_radius=0 color=0xff25252d

default=(
    padding_left=0
    padding_right=0
    icon.font="Maple Mono NF:Bold:14.0"
    label.font="Maple Mono NF:Semibold:14.0"
    icon.color=0xffAAB3C0
    label.color=0xffAAB3C0
    icon.padding_left=2
    icon.padding_right=2
    label.padding_left=2
    label.padding_right=2
    updates=on
)
sketchybar --default "${default[@]}"

##### Adding aeropsace layouts #####
# Add the aerospace events we specified in aerospace.toml
sketchybar --add event aerospace_workspace_change
sketchybar --add event aerospace_monitor_change

for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        display="$(
            v=$(aerospace list-windows --workspace "$sid" --format "%{monitor-appkit-nsscreen-screens-id}" | cut -c1)
            echo "${v:-1}"
            )" \
                drawing=off \
                background.color=0x44ffffff \
                background.corner_radius=0 \
                background.drawing=on \
                background.border_color=0xAAFFFFFF \
                background.border_width=0 \
                background.height=25 \
                icon="$sid" \
                icon.padding_left=10 \
                icon.shadow.distance=4 \
                icon.shadow.color=0xA0000000 \
                label.padding_right=20 \
                label.padding_left=0 \
                label.y_offset=-1 \
                label.shadow.drawing=off \
                label.shadow.color=0xA0000000 \
                label.shadow.distance=4 \
                click_script="aerospace workspace $sid" \
                script="$CONFIG_DIR/plugins/aerospace.sh $sid"
            done

# Load Icons on startup
for mid in $(aerospace list-monitors | cut -c1); do
    for sid in $(aerospace list-workspaces --monitor $mid --empty no); do
        apps=$(aerospace list-windows --workspace "$sid" | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')

        sketchybar --set space.$sid drawing=on

        icon_strip=" "
        if [ "${apps}" != "" ]; then
            while read -r app; do
                icon_strip+=" $($CONFIG_DIR/plugins/icon_map_fn.sh "$app")"
            done <<<"${apps}"
        else
            icon_strip=""
        fi
        sketchybar --set space.$sid label="$icon_strip"
    done
done

sketchybar --add item space_separator left \
    icon.padding_left=0 \
    label.drawing=off \
                background.drawing=off \
    script="$PLUGIN_DIR/space_windows.sh" \
    --subscribe space_separator aerospace_workspace_change front_app_switched space_windows_change aerospace_monitor_change

# Front app!!
sketchybar --add item front_app left \
    --set front_app icon.drawing=off \
    script="$PLUGIN_DIR/front_app.sh" \
    --subscribe front_app front_app_switched

sketchybar --add item clock right \
    --set clock update_freq=10 script="$PLUGIN_DIR/clock.sh" \
    --add item volume right \
    --set volume script="$PLUGIN_DIR/volume.sh" \
    --subscribe volume volume_change \
    --add item battery right \
    --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
    --subscribe battery system_woke power_source_change \

    sketchybar --update
    script="$PLUGIN_DIR/space_windows.sh" \
    --subscribe space_separator aerospace_workspace_change front_app_switched space_windows_change aerospace_monitor_change

# Front app!!
sketchybar --add item front_app left \
    --set front_app icon.drawing=off \
    script="$PLUGIN_DIR/front_app.sh" \
    --subscribe front_app front_app_switched

sketchybar --add item clock right \
    --set clock update_freq=10 script="$PLUGIN_DIR/clock.sh" \
    --add item volume right \
    --set volume script="$PLUGIN_DIR/volume.sh" \
    --subscribe volume volume_change \
    --add item battery right \
    --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
    --subscribe battery system_woke power_source_change \

    sketchybar --update
