set -a terminal-features "tmux-256color:RGB"
#set -ga terminal-overrides ",xterm-256color:Tc"

#set -as terminal-features ',linux:clipboard'
set -s set-clipboard on

set -g base-index 1

set -g history-limit 500000
set -g display-time 4000

# Set focus events
set-option -g focus-events on

# Renumber windows when one is closed
set -g renumber-windows on

set -g mouse off

set -g status-interval 1

set -g allow-rename on
set -g set-titles on
set -g automatic-rename off

# ==== Keybindings ====

unbind r

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

bind-key -n M-w kill-pane
bind-key -n M-t new-window
bind-key -n M-r command-prompt "rename-window %%"

bind-key -n M-d split-window -v -c "#{pane_current_path}"
bind-key -n M-D split-window -h -c "#{pane_current_path}"

bind-key -n M-Tab previous-window

bind-key -n M-N select-pane -L
bind-key -n M-E select-pane -D
bind-key -n M-O select-pane -U
bind-key -n M-I select-pane -R

bind-key -n M-A resize-pane -L
bind-key -n M-S resize-pane -D
bind-key -n M-H resize-pane -U
bind-key -n M-T resize-pane -R

bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9

bind -r s source-file ~/.tmux.conf

# ==== pane borders ====

set -g pane-border-style fg=white
set -g pane-active-border-style fg=blue

# ==== status ====

set -g status-bg black
set -g status-fg white
set -g message-style fg=white,bg=black
set-option -g status-position top
set-option -g status-style bg=default

set -g status-left ''
# set -g status-right '#(acpi -b | cut -d',' -f2 | tr -d ' ') %a %Y-%m-%d %H:%M'
set -g status-right '#[fg=white, bg=black]D:#(df / | awk "NR==2 {print \$5}") #(~/dotfiles/tmux/cpu.sh) #(~/dotfiles/tmux/ram.sh) B:#(cat /sys/class/power_supply/BAT0/capacity)% %Y-%m-%d %H:%M '

set -g window-status-current-format  '#[fg=black, bg=white] #I #W '
set -g window-status-format  ' #I #W '


